apiVersion: v2
name: stash-mysql-community
description: Stash MySQL Addon Community
type: application
version: v2020.09.16
appVersion: v2020.09.16
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
