apiVersion: v2
name: stash-mongodb-community
description: Stash MongoDB Addon Community Plan
type: application
version: v2020.09.29
appVersion: v2020.09.29
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
