apiVersion: v2
name: stash-postgres-community
description: Stash PostgreSQL Addon Community Plan
type: application
version: v2020.08.27
appVersion: v2020.08.27
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
